django_tut/urls.py
from django.conf.urls import url
from django.contrib import admin

from rango import views
from django.conf.urls import url
#Import the url objects to define the mapping
from django.contrib import admin
from django.conf.urls import include
#This is a method to h
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index1'),
    url(r'^rango/', include('rango.urls')),
    #The remainder of the string after stripping rango will be handled by rango.url.
    # Here, we import other URL configuration module. Not ending with $ but a /
    #reg, views. kwargs, name = None, prefix=''
]

rango/urls.py
from django.conf.urls import url
#This
import views
app_name = 'rango'

urlpatterns = [
    url(r'^$', views.index2, name='rango_main'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    #<category_name_slug> is a variable name, allows us to extract the value later on, [\w\-]+ is any alphanumeric sequence
]

rango/models.py
from __future__ import unicode_literals

from django.db import models
from django.template.defaultfilters import slugify

# Create your models here.

class Category(models.Model):
    #Define a list of fields
    name = models.CharField(max_length=128, unique=True)
    #Make the field unique
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    #A short label containing labels, characters, hyphen and underscore
    #blank = True allows blankspace


    class Meta:
        verbose_name_plural = 'categories'
        #Define how the plural should be, it is just a meta option, define everything but not a field

    def __str__(self):
        return self.name


    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
        # Super will give the base class of Category (the derived class)


class Page(models.Model):
    category = models.ForeignKey(Category)
    #Many Pages can be linked to one Category
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

rango/forms.py
from django import forms
from rango.models import Page, Category

class CategoryForm(forms.ModelForm):
    #Define different fields of the form
    name = forms.CharField(max_length=128, help_text="Please enter the category name")
    views = forms.IntegerField(widget=forms.HiddenInput(),initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.IntegerField(widget=forms.HiddenInput(),required=False)
    class Meta:
        #Provide connection between the ModelForm and model
        model=Category
        fields = ('name',)
        #Which field to be visible in our form, needs to be a tuple here

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page")
    url = forms.URLField(max_length=128, help_text="Please enter the URL of the page")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    #def clean(self):
    #    clean_data = self.cleaned_data
    #    url = clean_data.get('url')
    #    if url and not url.startswiths('http://'):
    #        url = 'http://'+url
    #        clean_data['url']=url
    #    return clean_data


    class Meta:
        model = Page
        #Associate the ModelForm with the Page model
        exclude = ('category',)

        #Note that category here is a field, defined in models.py
        #Equivalent to fields = ('title','url','views',)

rango/views.py
from django.shortcuts import render
#This method is used to update the template with the dict

# Create your views here.
from django.http import HttpResponse

from django.shortcuts import render
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm

def index(request):
    #First, get 5 categories after sorting in descending order
    all_cats = Category.objects.order_by('-likes')[:5]
    most_views_pages = Page.objects.order_by('-views')[:5]
    #Extract 5 most view category and send it to the context, '-' is the minus sign since the order_by will sort by increasing order
    context_dict = {'categories': all_cats, 'most_view_pages': most_views_pages}
    #'categories' is the name of the context variable

    #update_content = {'boldmessage': 'Crunchy, creamy, cookie, candy, cupcake!!!'}
    return render(request, 'rango/index.html', context=context_dict)

def show_category(request,category_name_slug):
    context_dict ={}
    #Dictionary for rendering the page
    try:
        #Get the current category
        cur_cat = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=cur_cat)
        context_dict['pages'] = pages
        context_dict['category'] = cur_cat

    except Category.DoesNotExist:
        context_dict['pages'] = None
        context_dict['category'] = None
    return render(request, 'rango/category.html', context=context_dict)

def index2(request):
    return HttpResponse("Hello, this is the second response from the Rango view.")

def about(request):
    about_content = {'your_name': 'Tan Huu Nguyen'}
    #Print out the request.method (GET/POST)
    print(request.method)
    #print out the user name
    print(request.user)
    return render(request, 'rango/about.html', context=about_content)

def add_category(request):
    form = CategoryForm()
    #Create a new form
    if request.method=='POST':
        #if this is an HTTP post
        form = CategoryForm(request.POST)
        if form.is_valid():
            cat = form.save(commit=True)
            #cat is an instance of the saved category
            return index(request)
        else:
            #Print the error to the terminal
            print(form.errors)
    #Handle the bad form, no form or new form
    return render(request, 'rango/add_category.html', {'form': form})


def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug = category_name_slug)
        #category_name_slug is provided by the URL
    except Category.DoesNotExist:
        category = None

    print("Name of the category: " + category.name)


    form = PageForm()
    #Note that the 'model' defined in PageForm is Page type
    if request.method=='POST':
        #if the form is submitted
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                #Get the 'page' object from the PageForm object
                page = form.save(commit=False)
                page.category = category #Add the category at this point, the category has been excluded
                #Category on the right is from the URL
                page.views=0
                page.save()
                return show_category(request, category_name_slug)
                #Quit the page form and display the current category
        else:
            print(form.errors)

    #If the use has not click the submit button, re-render the page
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)

templates/rango/about.html
{% extends 'rango/base.html'%}
{% load staticfiles%}
{% block title_block %}
    <title>Template homework for the about page</title>
{% endblock %}

{% block body_block %}
    <h1>This tutorial has been put togeher by {{ your_name }}.</h1>
    <div>
        Go back to the <br/>
        <a href="{% url 'index1' %}">Main </a> page. Otherwise, go to the <a href="{% url 'rango:rango_main'%}">Second page</a>
    </div>

    <div>
       <img src = "{%  static  "images/thetest.png" %}" alt =" About image"/>
    </div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% block title_block %}
    <title>Rango</title>
{% endblock %}

{% block body_block %}
     <h1>Add a category</h1>
        <div>
            <form id="category_form" method="POST" action="{% url 'rango:add_category' %}">
                {% csrf_token %}
                <!--Prevent erros on multiple submission-->
                {% for hidden in form.hidden_fields %}
                    <!--Note that 'form' is the key to the context variable of the view.add_category()-->
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}
                <input type="submit" name="submit" value="Create new category in the server" />
            </form>
        </div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% block title_block %}
    <title>Add a page</title>
{% endblock %}
{% block body_block %}
    {% if category %}
        <div>
            <form id="page_form" method="POST" action="{% url 'rango:add_page' category.slug %}">
                <!--Capture all the data and send to the URL /rango/category/{category.slug}/add_page/-->
                <!--Also note that the posted page should NOT have .html-->
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                    <!--Make sure that all hidden fields are display to avoid INVALID FORM errors-->
                {% endfor %}


                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}
                <input type="submit" name="submit" value="Create Page" />
            </form>
        </div>
        {% else %}
            The category you requested does not exist <br />
        {% endif %}

{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load rango_template_tags %}
<html>
    <title>All categories available</title>
    <div>
        {% block sidebar_block %}
            {% get_category_list category%}
            <!--This is a function defeind in rango_template_tags.py-->
        {% endblock %}
    </div>

    <head>
        <meta charset="UTF-8"/>
        <title>Rango -
        {% block title_block %}
            How to Tango with Django!

        {% endblock %}

        </title>
    </head>
    <body>
        <div>
            <!--Body of the template-->
            {% block body_block %}
            {% endblock %}
        </div>

        <hr />
        <div>
            <ul>
                <li><a href="{% url 'rango:add_category' %}">Add new Category</a> </li>
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'index1' %}">Index</a></li>
            </ul>
        </div>
    </body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}
<!--Inherits the template from base.html-->
{% load staticfiles %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
            <ul>
            {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
            </ul>


        {% else %}
            <strong>There is no pages in the current category</strong>
        {% endif %}
        <!-Add a new page to the current category-->
        <a href ="{% url 'rango:add_page' category.slug%}">Add a page</a>
    {% else %}
        The specified category cannot be found!
    {% endif %}

{% endblock %}

templates/rango/cats.html
<ul>
    {% if cats %}
        {% for c in cats %}
            {%  if c == act_cat %}
                <li><strong><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></strong></li>
            {% else %}
                <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
            {% endif %}
        {% endfor %}
    {% else %}
        <strong>There is no category present.</strong>
    {% endif %}
</ul>

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    <title>Rango title</title>
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        Hey there partner! <br/>
    </div>
    <h2>Most liked category</h2>
    <ul>
        {% if categories %}
            {% for category in categories %}
                <li><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>. #likes: {{ category.likes }}</li>
            {% endfor %}
        {% else %}
            <strong>There are no category present.</strong>
        {% endif %}
    </ul>
    <h2>Most viewed pages</h2>
    <ul>
        {% if most_view_pages %}
            {% for page in most_view_pages %}
                <li><a href = "{{ page.url }}">{{ page.title }}</a>, #views: {{ page.views }}</li>

            {% endfor %}
        {% endif %}
    </ul>
    <!--Add the add category page-->
    <a href="{% url 'rango:add_category' %}">Add a new category</a><br/>
    <img src = "{% static "images/mascot.jpeg" %}" alt ="Picture of Rango" /> <!--This call will replace static with STATIC_URL deffined in the settings.py--->

{% endblock %}